builder:
  track: dev

labels:
  app-group: estafette-ci
  type: library
  team: estafette
  language: golang

version:
  semver:
    major: 0
    minor: 8
    patch: 5
    releaseBranch: main

stages:
  lint-and-test:
    parallelStages:
      lint:
        image: golangci/golangci-lint:latest-alpine
        commands:
          - golangci-lint run --timeout 3m

      test:
        image: golang:1.20-alpine
        env:
          CGO_ENABLED: 1
          GOOS: linux
        commands:
          - apk add --update --no-cache build-base
          - go test -race ./...

  tag-revision:
    image: bitnami/git
    commands:
      - git tag v${ESTAFETTE_BUILD_VERSION}
      - git push origin v${ESTAFETTE_BUILD_VERSION}
    when:
      status == 'succeeded' &&
      branch == 'main'

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
      - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'
